workflows:
  ios-only:
    name: iOS IPA Build (Codemagic)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APPLE_ID: h.yuma0507@icloud.com         # ← あなたのApple ID
        APP_SPECIFIC_PASSWORD: Hyuma130507    # ← Apple IDのApp-specific password
    integrations:
      apple_developer_portal:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - hakutou0720@gmail.com                  # ← IPAのリンク送信先
